name: Macos compilation
on: [push]
jobs:
  qt6_6:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.*'
      - run: cmake -B build
      - run: cmake --build build -j
  qt6_5_LTS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.*'
      - run: cmake -B build
      - run: cmake --build build -j